# Generated by Django 5.1.7 on 2025-05-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('appointed_worker', models.CharField(max_length=255)),
                ('payment', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=5)),
                ('status', models.CharField(default='Не оплачено', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=255)),
            ],
        ),
    ]
