# Generated by Django 5.1.7 on 2025-05-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='time',
        ),
    ]
