# Generated by Django 5.1.7 on 2025-05-31 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='appointed_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.worker'),
        ),
    ]
